name: Mysql Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install XAMPP-81
        pip install requests bs4

    - name: Running MySql Server
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        7z x mysql.7z
        start "./mysql/bin/mysqld"
        timeout 10
        echo SET GLOBAL connect_timeout=28800 | mysql -u root
        echo SET GLOBAL interactive_timeout=28800 | mysql -u root
        echo SET GLOBAL wait_timeout=28800 | mysql -u root
        python main.py "mysql server:3306" 3306
