# This is a basic workflow to help you get started with Actions

name: Tor Server

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3    
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installing Dependencies
        run: |
            sudo apt install tor
            pip install requests bs4
            
      - name: Running a TOR server
        env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
        run: |  
            kill $(netstat -pl | grep 9050 | awk -F' ' '{ print $7}' | cut -d'/' -f 1)
            tor &
            python main.py "TOR Server:9050" 9050
