name: Xampp Server 8.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Installing Dependencies
      run: |
        choco install XAMPP-81
        pip install requests bs4

    - name: Running MySql Server
      env:
          DB_ADMIN_URL: ${{secrets.DB_ADMIN_URL}}
      run: |
        cd c:/xampp/
        start mysql_start.bat
        start apache_start.bat
        start filezilla_setup.bat
        timeout 5
        start filezilla_start.bat
        echo "SET GLOBAL connect_timeout=28800; SET GLOBAL interactive_timeout=28800; SET GLOBAL wait_timeout=28800; exit" | mysql -u root
        python main.py "xampp mysqldb:3306" 3306 "xampp localhost:80" 80 "xampp filezilla:22" 22
